import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import GlobalStylesProvider from "./Providers/GlobalStylesProvider";
import Sidebar from "./Components/Sidebar";
import { ClerkProvider} from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { Toaster } from 'react-hot-toast';
import '@mantine/core/styles.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { userId } = auth();

  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
            integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
          <ColorSchemeScript forceColorScheme="dark" />
        </head>
        <body>
          <GlobalStylesProvider>
            {userId && <Sidebar />}
            <main className="w-full p-4 border-2 border-solid border-[#f9f9f914] bg-[#212121]">
              <MantineProvider>
                <Toaster />
                {children}
                </MantineProvider>
            </main>
          </GlobalStylesProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
